### PR TITLE
Add pdbs to nuget spec file

### PR DESCRIPTION
**Pull request by rchiodo**

### CODE REVIEW

**Comment by rchiodo** [comment]
@jakebailey can you sign off on this? We're assuming you have write access.

We need to rev the nuget package for the parsing dll so that D17 of the python tools can use the parsing dll. Submission requirements state all dlls need a pdb

**Comment by jakebailey** [comment]
Hm, should this go to the ptvs branch? Not sure where ptvs gets it stuff from.

**Review by bschnurr — APPROVED** [review]

**Comment by jakebailey** [comment]
If `master` is where it's generated from, then LGTM, though I'm surprised to be modifying `master` at this point.

**Comment by jakebailey** [comment]
(Maybe we make a branch that's the support branch rather than committing to master?)

**Comment by bschnurr** [comment]
if i was adding new functionally I'd agree. but this is fixing an oversight.

**Pull request merged**
