### PR TITLE
Remove NoneType in favor of a consistent None, and remove completions which are also keywords

### LINKED ISSUE #1628: None shows twice in completion as None and __NoneType__
image

Fallout of #1624. The `__NoneType__` thing is coming from the scraper.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1628.

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
Looks like we need to bump folder version to `stubs.v3` since otherwiase old scrape of builtins will still be there

**Comment by MikhailArkhipov** [comment]
Approving pending stub version bump.

**Comment by jakebailey** [comment]
Ah, yeah. Should I be bumping the DB version too, and drop the old reference to NoneType completely?

**Comment by MikhailArkhipov** [comment]
Models technically didn't change so either we need to test with system caching on (i.e. cache with old code, then flip to new) or just bump up for safety.

**Pull request merged**
