### PR TITLE
Allow navigation to stubs

### LINKED ISSUE #1921: Go to Definition 'os.mkdir' error.
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): Python 2020.1.58038
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): false

## Actual behaviour
```
import os
os.mkdir('test')
```
click mkdir and Go to Definition would raise an error:
```
Unable to open 'python.posix.exe': Unable to read file (Error: File not found (vscode-remote://ssh-remote+dgpu/home/username/miniconda3/bin/python.posix.exe)).
```
## settings
```
{
    "editor.fontSize": 16,
    "editor.largeFileOptimizations": false,
    "terminal.integrated.inheritEnv": false,
    "workbench.iconTheme": "material-icon-theme",
    "files.autoSave": "afterDelay",
    "window.zoomLevel": 0,
    "debug.console.fontSize": 16,
    "terminal.integrated.fontSize": 16,
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    },
    "cmake.configureOnOpen": true,
    "C_Cpp.default.cppStandard": "c++11",
    "cmake.parallelJobs": 8,
    "workbench.sideBar.location": "left",
    "css.completion.completePropertyWithSemicolon": false,
    "workbench.statusBar.visible": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "C_Cpp.updateChannel": "Insiders",
    "C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 0}",
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "python.formatting.provider": "yapf",
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length=100",
        // "--ignore=E402,F401,E266"
    ],
    "python.formatting.yapfArgs": [
        "-p",
        "--style",
        "{ based_on_style: google, indent_width:4 , column_limit:100}"
    ],
    "python.dataScience.notebookFileRoot": "${fileDirname}",
    "python.jediMemoryLimit": -1,
    "python.linting.pylintEnabled": false,
    "python.jediEnabled": false,
}
```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
No harm in showing stub for compiled code or when otherwise source is not available. Also fixes issue when documentation on `os` parts was not transferred since `nt` or `posix` are not submodules of `os`.

Closes #1921

### CODE REVIEW

**Comment by jakebailey** [comment]
Does this need a test for the linked issue? I'm surprised `os.mkdir` is compiled. `os` itself is required to be written in Python, so `mkdir` probably gets exposed via a different module, but I'd still be surprised that it's compiled to that extent.

**Comment by MikhailArkhipov** [comment]
It is in `nt` which is compiled. Yeah, I can craft the test.

**Comment by jakebailey** [comment]
The original issue was not on Windows, so hopefully the same behavior occurs there too.

**Comment by jakebailey** [comment]
This appears to break the UpdateReferencesOnEdit test.

**Comment by jakebailey** [comment]
Specifically, the first `Should` gets only one reference rather than two; not sure which one is being dropped.

**Comment by MikhailArkhipov** [comment]
Fixed, unintentional change.

**Pull request merged**
