### PR TITLE
Fix hovering over parts of 'from A.B import C`

### LINKED ISSUE #569: Handle simple if statements when processing stubs
Typeshed's stubs contain many if statements to declare things based on the Python version and the system platform. In order to have the right type info, when analyzing stubs we should handle those checks. They're not complicated, and are usually like:

```python
if sys.version_info >= (3, 6): ...
if sys.platform == 'win32': ...
if sys.version_info >= (3, 3) and sys.platform != 'win32': ...
```

See:
- https://github.com/python/typeshed/blob/master/stdlib/3/os/__init__.pyi
- https://github.com/python/typeshed/blob/master/stdlib/3/os/path.pyi

Seems like it's all `sys.version_info` and `sys.platform`.

### LINKED ISSUE #607: Hover over complex module name in 'from ... import...' does not show correct info
`from os.path import join`

Hovering over `path` shows `os` and hovering over `join` just shows `join`. Tooltip should actually show `ntpath/posixpath` and the `join` information.

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #607
Fixes #569

- Implements handling of platform conditionals
- Implements specialization of os.path in conditionals
- Better handles hover in import/from import statements
- Fixes bug when variable was not defined in imports like `from A import B as C`
- Fixed bug when type of C in `import B as C` was not extracted (and documentation was empty) b/c `GetPythonType` did not handle variables.
- Several new tests for the above.

### CODE REVIEW

**Comment by jakebailey** [comment]
Is this intended?

image

**Comment by MikhailArkhipov** [comment]
Depends where you hover. Over `numpy`, no. Over `linalg`, yes.

**Comment by jakebailey** [comment]
I hovered over `numpy` on the second line, not `linalg`.

**Comment by MikhailArkhipov** [comment]
Ended up more complicated than originally planned.

**Comment by jakebailey** [comment]
I can't get the LS to start with this branch anymore:

```
[Error - 9:51:35 AM] Server initialization failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.Analysis.MemberExtensions.IsUnknown(IMember m) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Extensions\MemberExtensions.cs:line 26
   at Microsoft.Python.Analysis.Types.PythonFunctionOverload.AddReturnValue(IMember value) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Types\PythonFunctionOverload.cs:line 91
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.WalkAsync(ReturnStatement node, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 110
   at Microsoft.Python.Parsing.Ast.ReturnStatement.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\ReturnStatement.cs:line 36
   at Microsoft.Python.Parsing.Ast.SuiteStatement.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 46
   at Microsoft.Python.Parsing.Ast.SuiteStatement.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 46
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.EvaluateAsync(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 83
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.EvaluateScopeAsync(ScopeStatement target, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 81
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.ProcessClassBody(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 109
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.EvaluateClassAsync(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 70
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.EvaluateAsync(ScopeStatement target, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 92
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.ProcessClassBody(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 81
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.EvaluateClassAsync(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 70
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.EvaluateAsync(ScopeStatement target, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 92
   at Microsoft.Python.Analysis.Analyzer.ModuleWalker.WalkAsync(ClassDefinition node, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\ModuleWalker.cs:line 53
   at Microsoft.Python.Parsing.Ast.ClassDefinition.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\ClassDefinition.cs:line 144
   at Microsoft.Python.Parsing.Ast.SuiteStatement.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 46
   at Microsoft.Python.Parsing.Ast.PythonAst.WalkAsync(PythonWalkerAsync walker, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Parsing\Impl\Ast\PythonAst.cs:line 87
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.AnalyzeAsync(IDependencyChainNode node, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 149
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.AnalyzeDocumentAsync(IDocument document, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 59
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.LoadBuiltinTypesAsync(CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Modules\Resolution\MainModuleResolution.cs:line 144
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.LoadBuiltinTypesAsync(String root, IServiceManager sm, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\PythonInterpreter.cs:line 61
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.CreateAsync(InterpreterConfiguration configuration, String root, IServiceManager sm, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\Analysis\Ast\Impl\Analyzer\PythonInterpreter.cs:line 67
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\LanguageServer\Impl\Implementation\Server.cs:line 120
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in C:\Users\jabaile\mikhail-language-server\src\LanguageServer\Impl\LanguageServer.Lifetime.cs:line 36
```

**Pull request merged**
