### PR TITLE
Add .editorconfig file in addition to omnisharp.json #132

### PR DESCRIPTION
**Pull request by rv404674**
Added .editorconfig in addition to,  omnisharp.json as, .editorconfig is supported more widely.

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
Thanks!

**Comment by rv404674** [comment]
Thanks @MikhailArkhipov . Got any more 'good first issue for me' :)

**Comment by rv404674** [comment]
hey @lostmsu, got any new bugs for me.

**Comment by lostmsu** [comment]
@rv404674 I am actually just another external contributor :)

**Pull request merged**
