### PR TITLE
More null checks in NotifyAnalysisBegins

### PR DESCRIPTION
**Pull request by jakebailey**
Probably overkill, but #968 doesn't appear to have been enough.

### CODE REVIEW

**Comment by AlexanderSher** [comment]
IMO, fixes like that hide errors instead of fixing them. Not sure how hard is that in this case, but if nulls weren't expected originally, I'd prefer to find out why they are null, cause it may be a symptom of an invalid state.

**Comment by AlexanderSher** [comment]
For example:
- `Children` can't be null and can't contain null elements, because `AddChildScope` is used only in one place and always with instance
- `Variables` can't be null and can't contain null elements, because it is enumeration of `_variables` it is always assigned with the real `Variable` instance in either `DeclareVariable` or `LinkVariable`.

So the only thing that can be null is actually `GlobalScope`, which is legally null until it is set in `NotifyAnalysisComplete`

**Comment by jakebailey** [comment]
I agree. Here is the stack trace I've been seeing after the last PR:

```
   at Microsoft.Python.Analysis.Modules.PythonModule.<>c.<NotifyAnalysisBegins>b__106_0(IScope c)
   at Microsoft.Python.Core.EnumerableExtensions.TraverseDepthFirst[T](T root, Func`2 selectChildren)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Python.Analysis.Modules.PythonModule.NotifyAnalysisBegins()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(PythonAnalyzerEntry entry, Int32 version, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
```

**Comment by MikhailArkhipov** [comment]
So... `Children` cannot be null in both `Scope` and `EmptyScope` and `GlobalScope`. `Variables` is readonly property always initialized to `new VariableCollection`. `VariableCollection` always has `_variables` as `ConcurrentDictionary`...

**Comment by jakebailey** [comment]
Before #968 was:

```
   at Microsoft.Python.Analysis.Modules.PythonModule.<>c.<NotifyAnalysisBegins>b__106_1(IScope s)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Python.Analysis.Modules.PythonModule.NotifyAnalysisBegins()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode`1 node, AsyncCountdownEvent ace, Stopwatch stopWatch, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionCont
```

**Pull request merged**
