### PR TITLE
Ensure builtins module is created synchronously

### LINKED ISSUE #1697: print, others flagged as "Undefined variable" (requests being handled before initialization is complete?)
## Environment data

- Language Server version:  0.4.71.0 
- OS and version: Microsoft Windows [Version 10.0.18362.418]
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32

## Expected behaviour

print should NOT be flagged as "Undefined variable"

## Actual behaviour
print is flagged as "Undefined variable"

## Logs

```
N/A
```

## Code Snippet / Additional lnformation

vscodeUndefinedVar_print

```python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
For #1697

### CODE REVIEW

**Comment by jakebailey** [comment]
A few caching tests fail, weird.

**Comment by MikhailArkhipov** [comment]
Seems to be unrelated. Like `inspect` is looking for `Attribute` in typing while it is actually a named tuple in the `inspect` stub. I can look into that, but https://github.com/microsoft/python-language-server/pull/1757 supersedes caching anyway.

**Comment by MikhailArkhipov** [comment]
Combined with https://github.com/microsoft/python-language-server/pull/1757 all pass

**Comment by MikhailArkhipov** [comment]
Will leave #1697 open until confirmed.

**Pull request merged**
